service: cesta-basica-api

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    DBURL: ${${self:provider.stage}_DBURL}

  apiGateway:
    shouldStartNameWithService:true

plugins:
  - serverless-express

functions:
  healthCheck:
    handler: src/core/server.handler
    events:
      - http: ANY /
#      - http: 'ANY {proxy+}'
