name: aws-deployer

on:
  pull_request:
    types: [ closed ]
    branches: [develop, master]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI: false
    steps:
        - uses: actions/checkout@v2
        - name: build dependencies and deploy
          run: ./github_actions/build_and_deploy.py ${GITHUB_REF#refs/*/}
