# This is a basic workflow to help you get started with Actions

name: aws-deployer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: branch="${GITHUB_REF##*/}"
    if: github.event == 'push'
    name: aws-deploy
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@{branch}

      - name: deploy-static-S3
        run: ./lambdas/aws_deployer/aws_deployer.py {branch}
